### ISSUE TITLE
Unable to control the mixer with OSC.

### ISSUE THREAD

**Issue by KennethHoff** [falkTX/non#3]
I've been trying for the last couple of days to connect my Streamdeck with Non-mixer (technically, just change the mixer via the command line) to control the volume of the mixer tracks, and supposedly there is quite good OSC support, but there is no feedback no matter what I do; Am I missing some sort of library that non-mixer requires, or is it no longer working?

I use `oscsend` from liblo-tools, and specifically the following command:

> oscsend 0.0.0.0 14152 /strip/Unnamed/Gain/Mute

I've tried so many things, and nothing has any effect whatsoever.

If OSC is simply no longer working; Do you know of other NSM volume controls that can be changed from the CLI? (Either through the CLI directly - which would be ideal - or through some other means)

I'm using Pop!_Os 21.04

**Comment by falkTX** [comment]
Err, I am not maintaining NON, I only added LV2 support to non-mixer.

Sadly NON is an abandoned project by its own author, I suggest to look for alternatives.

**Comment by KennethHoff** [comment]
Jeez, that was a quick reply.

Thanks. Do you know of any good alternatives?

**Comment by falkTX** [comment]
Yeah sorry but NON already gave me far too many headaches.
I am keeping this code up as a mirror more than anything, I dont want to deal with the whole drama again...

**Comment by falkTX** [comment]
for alternatives, jack-mixer is recently picking up pace. but it does not do any plugins
